from django.urls import path 
from . import views 

urlpatterns = [ 
    path('', views.index, name= "books.index"), 
    path('list_books/', views.list_books, name= "books.list_books"), 
    path('<int:bookId>/', views.viewbook, name="books.view_one_book"), 
    path('aboutus/', views.aboutus, name="books.aboutus"), 
    path('html5/links/', views.links, name="books.links"),
    path('html5/text/formatting/', views.formatting, name="books.formatting"),
    path('html5/listing/', views.listing, name="books.listing"),
    path('html5/tables/', views.tables, name="books.tables"),
    path('search/',views.search),
    path('simple/query',views.simple_query),
    path('complex/query',views.lookup_query),
    path('lab8/task1', views.task1),
    path('lab8/task2', views.task2),
    path('lab8/task3', views.task3),
    path('lab8/task4', views.task4),
    path('lab8/task5', views.task5),
    path('lab8/task7', views.task7),
    path('lab9/task1', views.task1, name='lab9_task1'),
    path('lab9/task2', views.task2, name='lab9_task2'),
    path('lab9/task3', views.task3, name='lab9_task3'),
    path('lab9/task4', views.task4, name='lab9_task4'),
    path('lab9/task5', views.task5, name='lab9_task5'),
    path('lab9/task6', views.task6, name='lab9_task6'),
    path('lab9_part1/listbooks', views.list_books, name='list_books'),
    path('lab9_part1/addbook', views.add_book, name='add_book'),
    path('lab9_part1/editbook/<int:id>', views.edit_book, name='edit_book'),
    path('lab9_part1/deletebook/<int:id>', views.delete_book, name='delete_book'),
    path('lab9_part2/listbooks', views.list_books_p2, name='list_books_p2'),
    path('lab9_part2/addbook', views.add_book_p2, name='add_book_p2'),
    path('lab9_part2/editbook/<int:id>', views.edit_book_p2, name='edit_book_p2'),
    path('lab9_part2/deletebook/<int:id>', views.delete_book_p2, name='delete_book_p2'),
    path('students/list', views.student_list, name='student_list'),
    path('students/manage/', views.manage_student, name='manage_student'), 
    path('students/manage/<int:id>/', views.manage_student, name='manage_student'), 
    path('students/delete/<int:id>/', views.delete_student, name='delete_student'),
    path('students2/list/', views.student_list_p2, name='student_list_p2'),
    path('students2/manage/', views.manage_student_p2, name='manage_student_p2'),
    path('students2/manage/<int:id>/', views.manage_student_p2, name='manage_student_p2'),
    path('students2/delete/<int:id>/', views.delete_student_p2, name='delete_student_p2'),
    path('gallery/add/', views.add_book_gallery, name='add_book_gallery'),
    path('gallery/list/', views.book_gallery_list, name='book_gallery_list'),
] 